MODEL:
  NAME: "deeplabv3plus_resnet101_iseg"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: True
  NUM_CLASSES: 6
DATASETS:
  SOURCE_TRAIN: "potsdam_train"
  TARGET_TRAIN: "vaihingen_train"
  TEST: "vaihingen_test"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (512, 512)
  TARGET_INPUT_SIZE_TRAIN: (512, 512)
  INPUT_SIZE_TEST: (512, 512)
SOLVER:
  BASE_LR: 2.5e-4
  MAX_ITER: 39063
  STOP_ITER: 25000
  BATCH_SIZE: 2
  CONSISTENT_LOSS: 0.1
  NEGATIVE_LOSS: 1.0
  NEGATIVE_THRESHOLD: 0.05
  CHECKPOINT_PERIOD: 1000

ACTIVE:
  NAME: 'EASE-ADA'
  SELECT_ITER: [3000, 6000, 9000, 12000, 15000]
  PIXELS: 40
  RADIUS_K: 10

WTS_ADA:
  SRC_AUG: False

INTERACTIVE:
  POSITIVE_THRESHOLD: 0.01
  POSITIVE_LOSS: 0.8
  WARMUP_ITER: 3000
  POINT_LOSS: 2.0
  DOWN_LR: 0.05
  ERROR_THRESHOLD: 0.30
  max_num_next_clicks: 40
  select: 'SFAL'
